# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lyricwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 748)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setToolTipDuration(-1)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topframe = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.topframe.sizePolicy().hasHeightForWidth())
        self.topframe.setSizePolicy(sizePolicy)
        self.topframe.setMinimumSize(QtCore.QSize(0, 50))
        self.topframe.setMaximumSize(QtCore.QSize(16777215, 50))
        self.topframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topframe.setObjectName("topframe")
        self.verticalLayout_3.addWidget(self.topframe)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftframe = QtWidgets.QFrame(self.centralwidget)
        self.leftframe.setMinimumSize(QtCore.QSize(200, 0))
        self.leftframe.setMaximumSize(QtCore.QSize(200, 16777215))
        self.leftframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftframe.setObjectName("leftframe")
        self.openfilebutton = QtWidgets.QPushButton(self.leftframe)
        self.openfilebutton.setGeometry(QtCore.QRect(110, 380, 41, 41))
        self.openfilebutton.setText("")
        self.openfilebutton.setObjectName("openfilebutton")
        self.horizontalLayout.addWidget(self.leftframe)
        self.mainframe = QtWidgets.QFrame(self.centralwidget)
        self.mainframe.setLineWidth(0)
        self.mainframe.setObjectName("mainframe")
        self.ori_webEngineView = QtWebEngineWidgets.QWebEngineView(self.mainframe)
        self.ori_webEngineView.setGeometry(QtCore.QRect(-20, 0, 551, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ori_webEngineView.sizePolicy().hasHeightForWidth())
        self.ori_webEngineView.setSizePolicy(sizePolicy)
        self.ori_webEngineView.setMinimumSize(QtCore.QSize(0, 30))
        self.ori_webEngineView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ori_webEngineView.setSizeIncrement(QtCore.QSize(0, 0))
        self.ori_webEngineView.setStyleSheet("font: 14pt \"Songti SC\";")
        self.ori_webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.ori_webEngineView.setObjectName("ori_webEngineView")
        self.lrc_textBrowser = QtWidgets.QTextBrowser(self.mainframe)
        self.lrc_textBrowser.setGeometry(QtCore.QRect(550, 0, 281, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lrc_textBrowser.sizePolicy().hasHeightForWidth())
        self.lrc_textBrowser.setSizePolicy(sizePolicy)
        self.lrc_textBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.lrc_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lrc_textBrowser.setAutoFillBackground(True)
        self.lrc_textBrowser.setStyleSheet("")
        self.lrc_textBrowser.setObjectName("lrc_textBrowser")
        self.horizontalLayout.addWidget(self.mainframe)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.bottomframe = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(80)
        sizePolicy.setHeightForWidth(self.bottomframe.sizePolicy().hasHeightForWidth())
        self.bottomframe.setSizePolicy(sizePolicy)
        self.bottomframe.setMinimumSize(QtCore.QSize(0, 80))
        self.bottomframe.setMaximumSize(QtCore.QSize(16777215, 80))
        self.bottomframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomframe.setObjectName("bottomframe")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottomframe)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(40)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.bottomframe)
        self.frame.setMinimumSize(QtCore.QSize(180, 78))
        self.frame.setMaximumSize(QtCore.QSize(180, 78))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.playbutton = QtWidgets.QPushButton(self.frame)
        self.playbutton.setGeometry(QtCore.QRect(70, 14, 50, 50))
        self.playbutton.setText("")
        self.playbutton.setObjectName("playbutton")
        self.pausebutton = QtWidgets.QPushButton(self.frame)
        self.pausebutton.setGeometry(QtCore.QRect(70, 14, 50, 50))
        self.pausebutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pausebutton.setText("")
        self.pausebutton.setObjectName("pausebutton")
        self.prevbutton = QtWidgets.QPushButton(self.frame)
        self.prevbutton.setGeometry(QtCore.QRect(10, 14, 50, 50))
        self.prevbutton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevbutton.setText("")
        self.prevbutton.setFlat(False)
        self.prevbutton.setObjectName("prevbutton")
        self.nextbutton = QtWidgets.QPushButton(self.frame)
        self.nextbutton.setGeometry(QtCore.QRect(130, 14, 50, 50))
        self.nextbutton.setText("")
        self.nextbutton.setObjectName("nextbutton")
        self.horizontalLayout_2.addWidget(self.frame)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.progress_slider = QtWidgets.QSlider(self.bottomframe)
        self.progress_slider.setOrientation(QtCore.Qt.Horizontal)
        self.progress_slider.setObjectName("progress_slider")
        self.horizontalLayout_5.addWidget(self.progress_slider)
        self.songtimelabel = QtWidgets.QLabel(self.bottomframe)
        self.songtimelabel.setObjectName("songtimelabel")
        self.horizontalLayout_5.addWidget(self.songtimelabel)
        self.frame_2 = QtWidgets.QFrame(self.bottomframe)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.vmutebutton = QtWidgets.QPushButton(self.frame_2)
        self.vmutebutton.setGeometry(QtCore.QRect(30, 19, 36, 36))
        self.vmutebutton.setText("")
        self.vmutebutton.setObjectName("vmutebutton")
        self.volumebutton = QtWidgets.QPushButton(self.frame_2)
        self.volumebutton.setGeometry(QtCore.QRect(30, 19, 36, 36))
        self.volumebutton.setText("")
        self.volumebutton.setObjectName("volumebutton")
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.volumeslider = QtWidgets.QSlider(self.bottomframe)
        self.volumeslider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeslider.setObjectName("volumeslider")
        self.horizontalLayout_5.addWidget(self.volumeslider)
        self.frame_3 = QtWidgets.QFrame(self.bottomframe)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.playbackbutton_ran = QtWidgets.QPushButton(self.frame_3)
        self.playbackbutton_ran.setGeometry(QtCore.QRect(0, 10, 51, 51))
        self.playbackbutton_ran.setObjectName("playbackbutton_ran")
        self.playbackbutton_seq = QtWidgets.QPushButton(self.frame_3)
        self.playbackbutton_seq.setGeometry(QtCore.QRect(50, 10, 51, 51))
        self.playbackbutton_seq.setObjectName("playbackbutton_seq")
        self.playbackbutton_singleloop = QtWidgets.QPushButton(self.frame_3)
        self.playbackbutton_singleloop.setGeometry(QtCore.QRect(100, 10, 51, 51))
        self.playbackbutton_singleloop.setObjectName("playbackbutton_singleloop")
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.horizontalLayout_5.setStretch(0, 5)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.setStretch(3, 2)
        self.horizontalLayout_5.setStretch(4, 2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 9)
        self.verticalLayout_3.addWidget(self.bottomframe)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1059, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.songtimelabel.setText(_translate("MainWindow", "Time"))
        self.playbackbutton_ran.setText(_translate("MainWindow", "随机"))
        self.playbackbutton_seq.setText(_translate("MainWindow", "顺序"))
        self.playbackbutton_singleloop.setText(_translate("MainWindow", "单曲"))

from PyQt5 import QtWebEngineWidgets
