# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lyricwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1018, 705)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setToolTipDuration(-1)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topframe = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.topframe.sizePolicy().hasHeightForWidth())
        self.topframe.setSizePolicy(sizePolicy)
        self.topframe.setMinimumSize(QtCore.QSize(0, 50))
        self.topframe.setMaximumSize(QtCore.QSize(16777215, 50))
        self.topframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topframe.setObjectName("topframe")
        self.verticalLayout_3.addWidget(self.topframe)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftframe = QtWidgets.QFrame(self.centralwidget)
        self.leftframe.setMinimumSize(QtCore.QSize(240, 0))
        self.leftframe.setMaximumSize(QtCore.QSize(240, 16777215))
        self.leftframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftframe.setObjectName("leftframe")
        self.horizontalLayout.addWidget(self.leftframe)
        self.mainframe = QtWidgets.QFrame(self.centralwidget)
        self.mainframe.setObjectName("mainframe")
        self.ori_webEngineView = QtWebEngineWidgets.QWebEngineView(self.mainframe)
        self.ori_webEngineView.setGeometry(QtCore.QRect(0, -20, 271, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ori_webEngineView.sizePolicy().hasHeightForWidth())
        self.ori_webEngineView.setSizePolicy(sizePolicy)
        self.ori_webEngineView.setMinimumSize(QtCore.QSize(0, 30))
        self.ori_webEngineView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ori_webEngineView.setSizeIncrement(QtCore.QSize(0, 0))
        self.ori_webEngineView.setStyleSheet("font: 14pt \"Songti SC\";")
        self.ori_webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.ori_webEngineView.setObjectName("ori_webEngineView")
        self.lrc_textBrowser = QtWidgets.QTextBrowser(self.mainframe)
        self.lrc_textBrowser.setGeometry(QtCore.QRect(270, 0, 501, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lrc_textBrowser.sizePolicy().hasHeightForWidth())
        self.lrc_textBrowser.setSizePolicy(sizePolicy)
        self.lrc_textBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.lrc_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lrc_textBrowser.setAutoFillBackground(True)
        self.lrc_textBrowser.setStyleSheet("")
        self.lrc_textBrowser.setObjectName("lrc_textBrowser")
        self.openfilebutton = QtWidgets.QPushButton(self.mainframe)
        self.openfilebutton.setGeometry(QtCore.QRect(30, 380, 41, 41))
        self.openfilebutton.setText("")
        self.openfilebutton.setObjectName("openfilebutton")
        self.horizontalLayout.addWidget(self.mainframe)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.bottomframe = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(80)
        sizePolicy.setHeightForWidth(self.bottomframe.sizePolicy().hasHeightForWidth())
        self.bottomframe.setSizePolicy(sizePolicy)
        self.bottomframe.setMinimumSize(QtCore.QSize(0, 80))
        self.bottomframe.setMaximumSize(QtCore.QSize(16777215, 80))
        self.bottomframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomframe.setObjectName("bottomframe")
        self.prevbutton = QtWidgets.QPushButton(self.bottomframe)
        self.prevbutton.setGeometry(QtCore.QRect(0, 17, 45, 45))
        self.prevbutton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevbutton.setText("")
        self.prevbutton.setFlat(False)
        self.prevbutton.setObjectName("prevbutton")
        self.playbutton = QtWidgets.QPushButton(self.bottomframe)
        self.playbutton.setGeometry(QtCore.QRect(50, 16, 50, 50))
        self.playbutton.setText("")
        self.playbutton.setObjectName("playbutton")
        self.nextbutton = QtWidgets.QPushButton(self.bottomframe)
        self.nextbutton.setGeometry(QtCore.QRect(105, 17, 45, 45))
        self.nextbutton.setText("")
        self.nextbutton.setObjectName("nextbutton")
        self.progress_slider = QtWidgets.QSlider(self.bottomframe)
        self.progress_slider.setGeometry(QtCore.QRect(160, 30, 431, 20))
        self.progress_slider.setOrientation(QtCore.Qt.Horizontal)
        self.progress_slider.setObjectName("progress_slider")
        self.songtimelabel = QtWidgets.QLabel(self.bottomframe)
        self.songtimelabel.setGeometry(QtCore.QRect(590, 30, 100, 20))
        self.songtimelabel.setObjectName("songtimelabel")
        self.pausebutton = QtWidgets.QPushButton(self.bottomframe)
        self.pausebutton.setGeometry(QtCore.QRect(50, 16, 50, 50))
        self.pausebutton.setText("")
        self.pausebutton.setObjectName("pausebutton")
        self.volumeslider = QtWidgets.QSlider(self.bottomframe)
        self.volumeslider.setGeometry(QtCore.QRect(740, 30, 101, 20))
        self.volumeslider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeslider.setObjectName("volumeslider")
        self.volumebutton = QtWidgets.QPushButton(self.bottomframe)
        self.volumebutton.setGeometry(QtCore.QRect(700, 20, 40, 40))
        self.volumebutton.setText("")
        self.volumebutton.setObjectName("volumebutton")
        self.vmutebutton = QtWidgets.QPushButton(self.bottomframe)
        self.vmutebutton.setGeometry(QtCore.QRect(700, 20, 40, 40))
        self.vmutebutton.setText("")
        self.vmutebutton.setObjectName("vmutebutton")
        self.verticalLayout_3.addWidget(self.bottomframe)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1018, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.songtimelabel.setText(_translate("MainWindow", "Time"))

from PyQt5 import QtWebEngineWidgets
